plugins {
    id 'jacoco'
    id 'org.sonarqube' version '3.0'
    id 'com.gradle.plugin-publish' version '1.2.0'
    id 'be.vbgn.ci-detect' version '0.5.0'
    id 'com.netflix.nebula.integtest' version '13.0.1'
    id "io.freefair.lombok" version "9.2.0"
    id 'groovy'
}

group 'eu.xenit.gradle'

lombok {
    version = "1.18.30"
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

repositories {
    mavenCentral()
    gradlePluginPortal()
}

dependencies {
    implementation 'org.jreleaser:org.jreleaser.gradle.plugin:1.19.0'

    integTestImplementation "commons-io:commons-io:2.8.0"
    testImplementation 'junit:junit:4.12'
    testImplementation 'org.mockito:mockito-core:3.7.7'
    testImplementation 'com.github.stefanbirkner:system-rules:1.19.0'
}

gradlePlugin {
    vcsUrl = "https://github.com/xenit-eu/enterprise-conventions-gradle-plugin"
    website = vcsUrl
    plugins {
        privatePlugin {
            id = 'eu.xenit.enterprise-conventions.private'
            implementationClass = 'eu.xenit.gradle.enterprise.conventions.PrivatePlugin'
            displayName = "Xenit private conventions plugin"
            description = "Configures conventions for Xenit private packages"
        }
        ossPlugin {
            id = 'eu.xenit.enterprise-conventions.oss'
            implementationClass = 'eu.xenit.gradle.enterprise.conventions.OssPlugin'
            displayName = "Xenit OSS conventions plugin"
            description = "Configures conventions for Xenit open source packages"
        }
        signingExtensionsPlugin {
            id = 'eu.xenit.enterprise-conventions.ext.signing'
            implementationClass = 'eu.xenit.gradle.enterprise.conventions.extensions.signing.AutomaticSigningPlugin'
            displayName = "Xenit conventions plugin: Signing extension"
            description = "Automatically configures artifact signing"
        }
        centralPublishPlugin {
            id = 'eu.xenit.enterprise-conventions.ext.maven-central-publish'
            implementationClass = 'eu.xenit.gradle.enterprise.conventions.extensions.mavencentral.publish.MavenCentralPublishPlugin'
            displayName = "Xenit conventions plugin: Maven Central publish"
            description = "Configures publication to Maven Central using the Sonatype Central Portal"
        }
        centralRequirementsPlugin {
            id = 'eu.xenit.enterprise-conventions.ext.maven-central-requirements'
            implementationClass = 'eu.xenit.gradle.enterprise.conventions.extensions.mavencentral.requirements.MavenCentralRequirementsCheckPlugin'
            displayName = "Xenit conventions plugin: Maven Central requirements check"
            description = "Performs pre-publish check for requirements for publishing to Maven Central, also when publishing snapshots"
        }
        dockerImageLabelsPlugin {
            id = 'eu.xenit.enterprise-conventions.ext.docker-image-labels'
            implementationClass = 'eu.xenit.gradle.enterprise.conventions.extensions.dockerimagelabels.DockerImageLabelsPlugin'
            displayName = "Xenit conventions plugin: OCI source labels for Docker images"
            description = "Adds OCI annotations to Docker images indicating the source repository and commit"
        }
    }
    testSourceSets(sourceSets.integTest)
}

integrationTest {
    if (gradle.startParameter.offline) {
        systemProperty "eu.xenit.enterprise.conventions.integration.gradle-offline", "true"
    }
}
